# Generated by Django 5.2.3 on 2025-08-27 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qualification_type', models.CharField(choices=[('driving_license', 'Driving License'), ('PSV_license', 'PSV License')], default='driving_license', max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ['-issue_date'],
            },
        ),
    ]
