# Generated by Django 5.2.3 on 2025-08-19 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='id',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
