# Generated by Django 5.2.3 on 2025-08-19 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0002_remove_qualification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
