# Generated by Django 5.2.3 on 2025-08-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0003_qualification_id_and_more'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS vehiclequalifications_vehiclequalification;"),
    ]
