# Generated by Django 5.2.3 on 2025-08-14 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualifications', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiclequalification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclequalification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_qualifications', to='qualifications.qualification')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='vehicles.vehicle')),
            ],
        ),
    ]
